### ISSUE TITLE
Incorrect error message when non-existent customers are deleted

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#144]
**Describe the bug**
When we delete a non-existent customer, we receive an incorrect error message stating "Customer has been deleted!"

**To Reproduce**
1. Go to home page.
2. Click on Search to get all entries.
3. Click Clear.
4. Fill in any customer ID which was not listed in all entries in the Customer ID field.
5. Click Delete.

**Expected behavior**
Response expected - “Customer with id 'id-number' was not found." when deleting a non-existent customer.

**Observed behavior**
Response received - “Customer has been deleted!"

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63ed388efc49e3170307cc8b/640403a7-f492-4cce-bdcb-2295e54d0c20)

**Additional context**
NA

**Comment by Akshama** [comment]
Not needed - Discussed with Professor on Slack.
