### ISSUE TITLE
Customer ID missing in delete response message

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#147]
**Describe the bug**
Customer ID missing in delete response message

**To Reproduce**
1. Go to Home Page
2. Click on Search to get all entries
3. Click Clear
4. Fill in any valid customer ID (any among the entries listed above) in the Customer ID field.
5. Click Delete

**Expected behavior**
“Customer has been deleted!”

**Observed behavior**
“Customer with id '1902' has been deleted.”

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63ed388efc49e3170307cc8b/3d131f17-45e6-4659-b4b1-27f2bfdd6a6c)

**Additional context**
NA

**Comment by Akshama** [comment]
Not needed - Discussed with Professor on Slack.
