### ISSUE TITLE
Build Logs Retrieving API for Actions on Customer Information

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#15]
**As a** Developer 
**I need** to deliver Logs via an API service 
**So that** auditors/management can track creation, modification and deletion of customers for Auditing purposes.

### Details and Assumptions
Logs should include information about the customer id, name, action, actor id, updated data and timestamp

 ### Acceptance Criteria  
   
 ```gherkin
Given Customer not created
When creating new customer
Then creation action should be logged

Given Customer record been created
When modifying customer information
Then the modification action should be logged

Given Customer record been created
When deleting customer information
Then the deletion action should be logged

```

**Comment by ayushjainid** [comment]
Out of scope/Irrelevant.
