### ISSUE TITLE
Build the Root APIs Web Page

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#16]
**As** a Developer 
**I need** create a web page for the Root (/) path of the API services 
**So that** users can get details about the underlying services

### Details and Assumptions
Root web page should display all the underlying services with their description, and provide users URLs to access them

 ### Acceptance Criteria  
   
 ```gherkin
Given user visits the Root web page
When the web page loads
Then it should provide documentation about the underlying services  
```

**Comment by mwj10** [comment]
**As** a Developer **I need ** create a web page for the Root (/) path of the API services 
**to** provide documentation about the underlying services and how to access them

**Comment by ayushjainid** [comment]
Out of scope/Irrelevant.

**Comment by ayushjainid** [comment]
(Correction) Completed as a part of #31.
