### ISSUE TITLE
Update the routes.py file to contain the Flask service routes

### ISSUE THREAD

**Issue by wannabeOG** [CSCI-GA-2820-SP23-003/customers#18]
**As a** developer
**I need** to update the routes.py file to contain the Flask Service routes
**So that** I can perform the necessary service operations.
   
 ### Details and Assumptions
 routes.py already has the starter code for the initialization.
   
 ### Acceptance Criteria  
 ```gherkin
 Given routes.py is updated to contain the Flask Service routes,
When the routes are called through the API service, 
The operation works as expected
```

**Comment by sreevishnu211** [comment]
Any minor changes in routes.py
