### ISSUE TITLE
Create Customer Profile Web Page

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#29]
**As a** Customer
**I need** to view my stored information
**So that** I can update it when needed 

### Details and Assumptions
It should be easy for the customer to view their profile information as listed in issue #3.

 ### Acceptance Criteria  
   
 ```gherkin
Given Customer requests access to Profile Information
When the user is authorized
Then the system should display the Profile information

Given Customer requests access to Profile Information
When the user is not authorized
Then the system should display a Not Authorized message
```

**Comment by ayushjainid** [comment]
Completed as a part of #72.
