### ISSUE TITLE
Design Customers Database Schema

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#3]
**As a** Customer Service Manager 
**I need** to design the Customer Schema 
**So that** developers can create the customer database object in PostgresSQL.

**Details and Assumptions**
Customer main information will include:
Id (INT, INCRM, UNIQUE)
First Name
Last Name
User Name/Email (Unique)
Password (Hashed)
Phone Number (Optional - Unique)

**Acceptance Criteria**

 ```gherkin
Given the service is running and customer not created
When requesting creation of new customer
Then Customer record will be created and customer will be assigned to an ID
```

**Comment by sreevishnu211** [comment]
**As a** Developer
**I need**  a Customers Information Model  
**So that** I can standardize the way I store Customer Data.
   
 ### Details and Assumptions
The model should accommodate:
- First Name
- Last Name
- Mobile Number
   
 ### Acceptance Criteria  
The Model should accommodate all Customers data. And it should be reviewed by another team member.

**Comment by sreevishnu211** [comment]
What are your thoughts on using mobile number as our customer id?
Its unique and most platforms nowadays allow their customers to login using just their mobile numbers.

**Comment by Akshama** [comment]
Yes, I think it's a good idea. We can also add that to our Customer Creation story that the {id} provided with the URL /customers/{id} will be the mobile number.

**Comment by mwj10** [comment]
I suggest to make the Id to be Unique Incremental number. There are multiple reasons for this, such as customers change their phone numbers, have multiple phone numbers and might not want to share their phone numbers due to privacy. I found this design to be the most common approach for id when it comes to design the database.

**Comment by sreevishnu211** [comment]
I agree.
But the use case I thought of was, lets say youre an API user who uses the /customers/< id > API. If we use an incremental number as our ID, you wont know whats the ID of a customer is, so it becomes harder for you to call /customers/< id >.
For ex:
If youre a service agent helping a customer with something regarding their account, and youre on the phone with the customer. Both the customer and you, wont know the ID. Whereas if it was something that atleast one of you knew, like an email or mobile number, you can query /customers/< id >.

Let me know your thoughts on this.

**Comment by mwj10** [comment]
I understand the concern here. Usually, systems don't hide the auto assigned ID from their users which what we can do here. Moreover, we can build the functionality around the user name or even their email. Maybe it's good idea that we also create a simple Profile web page for the customers.

Let me know what you think.

**Comment by Akshama** [comment]
I agree, creating a profile web page/simple HTML form to POST data for the new customer record is a good idea.
Fields: Name, email, phone number, username and password, address(es) for each customer. We can keep some fields optional based on our decision of the unique key.

**Comment by mwj10** [comment]
Agree, we can proceed and make these fields as optional then adopt if a case rises in the future.

**Comment by sreevishnu211** [comment]
Agreed. Will make the changes in the issues early tomorrow.

**Comment by mwj10** [comment]
**As a** Developer **I need** to design the Customer Information Model **So that** development team can review.

**Details and Assumptions**
Customer main information will include:
Id (INT, INCRM, UNIQUE)
First Name
Last Name
User Name
Password
Email
Phone Number

**Acceptance Criteria**

 ```gherkin
 Given the service is running and customer not created
 When customer's email or phone number not used before
 Then Customer record will be created and customer will be assigned to an ID

 Given the service is running and customer not created
 When customer's email or phone number was used before
 Then Customer should be notified to use different email or phone number accordingly
```

**Comment by Akshama** [comment]
I feel we should rename "Information Model" to Database schema, what do you think?

**Comment by mwj10** [comment]
I agree, I suggest to rename to Customer schema, since another issue been created to cover the Address part.

**Comment by sreevishnu211** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-spring23-003-63e5271972c0b5edc5ad900d/issues/CSCI-GA-2820-SP23-003/customers/3?planning-poker) with Zenhub @Akshama @ayushjainid @mwj10 @wannabeOG
