### ISSUE TITLE
Authenticate a Customer

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#30]
**As an** API Developer
**I need** to authenticate Customers
**So that** other services can guarantee that a Customer is authorized to make actions

### Details and Assumptions
Customer should authenticate themselves using User Name and Password

 ### Acceptance Criteria  
   
 ```gherkin
Given customer request service
When customer is not authenticated
Then the system should deliver missing authentication error message

Given customer request service
When customer is authenticated
Then the system should authorize request to proceed
```

**Comment by ayushjainid** [comment]
Out of scope/Irrelevant.
