### ISSUE TITLE
Design Logs Schema

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#35]
**As a** Developer
**I need** to store logs for actions done on customer information
**So that** any changes can be tracked for incident handling
   
 ### Details and Assumptions
Logs information should include:
- Customer ID
- Action (Delete/Modify/Update)
- Timestamp
- Actor ID (Optional for Now)

 ### Acceptance Criteria  
   
 ```gherkin
 Given service is running
 When customer record is being created
 Then creation event will be logged

 Given service is running
 When customer record is being modified
 Then modification event will be logged

 Given service is running
 When customer record is being deleted
 Then deletion event will be logged
```

**Comment by ayushjainid** [comment]
Out of scope/Irrelevant.
