### ISSUE TITLE
Create a .github/workflows/bdd.yml file and Configure GitHub Actions to run the integration test cases at Push to Master/Pull Request Submission

### ISSUE THREAD

**Issue by Akshama** [CSCI-GA-2820-SP23-003/customers#61]
**As a** developer
**I need** to be able to see if any PR/Push is passing the required tests
**So that** I can be sure that the new changes are not breaking older functionality
   
 ### Details and Assumptions
 * Create a .github/workflows/bdd.yml file
 * Configure GitHub Actions to run the unit test cases every time someone pushes to
the master branch or submits a Pull Request
 * All this while maintaining 95%+ code coverage
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a developer makes some code changes
When a PR is raised for those changes or it is pushed to the master branch
Then Github Actions should check if all the tests are passing or not
```

**Comment by ayushjainid** [comment]
95%+ code coverage to be confirmed.
