### ISSUE TITLE
Add prod namespace to the Kubernetes cluster 

### ISSUE THREAD

**Issue by Akshama** [CSCI-GA-2820-SP23-003/customers#63]
**As a** API developer
**I need** add a prod namespace to the Kubernetes cluster 
**So that** I can deploy my services in a prod environment  
   
 ### Details and Assumptions
 * Cluster is up and running
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the cluster is up and running
 When I add a prod namespace to the Kubernetes cluster 
 Then I can deploy my services in a prod environment
```

**Comment by mwj10** [comment]
Dev namespace been created and ImagePullSecret been copied to the namespace

**Comment by Akshama** [comment]
![image.png](https://images.zenhubusercontent.com/63e52d33513305367f4b28bf/42c846c2-378a-42a4-a9a9-ae0ac68e33aa)

**Comment by Akshama** [comment]
Looks good.
