### ISSUE TITLE
Deploy the service to the Kubernetes cluster using kubectl command

### ISSUE THREAD

**Issue by Akshama** [CSCI-GA-2820-SP23-003/customers#66]
**As a** API developer
**I need** to use kubectl command
**So that** I can deploy services to the Kubernetes cluster
   
 ### Details and Assumptions
 * Cluster is up and running

 ### Acceptance Criteria  
   
 ```gherkin
Given the required files are updated to deploy service on Kubernetes
When `kubectl apply -f deploy`is issued
Then the Customer service is successfully deployed to Kubernetes
```

**Comment by Akshama** [comment]
![image.png](https://images.zenhubusercontent.com/63e52d33513305367f4b28bf/6d9081f8-4fe1-416a-9ff6-8776fc580fec)
Deployment, service and postgresql is successfully deployed in the dev Namespace. 
Once the pipeline is setup on IBM Cloud, we'll have automatic deployment in the namespaces.
We are good for this story/sprint.

**Comment by ayushjainid** [comment]
Validated the same in the Sprint call.
