### ISSUE TITLE
Specify Port for the IP Address and of Worker Node to Connect to the Service via the URL

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#71]
**As a** Developer
**I need** to Specify the port of the IP Address of the Worker Node
**So that** it can connect users to the Service

**Details and Assumptions**
* Worker node been created and IP address is available
*  Get the IP address of the worker node and combine it with the port to go to the URL of the service and make sure that it works. Development port is: 31001 and the Production port is:31002

**Acceptance Criteria**
Accessing the IP address with the specified port will connect users to the service

 ```gherkin
Given Worker Node is live
When Users try to access the service
Then they will be connected via the specified port
 ```

**Comment by Akshama** [comment]
![image.png](https://images.zenhubusercontent.com/63e52d33513305367f4b28bf/c920c137-c5df-4cfb-b788-009a5ddeaafc)
![image.png](https://images.zenhubusercontent.com/63e52d33513305367f4b28bf/ec7735e3-e5f3-4c28-978e-4207b126ed9d)
Service is up and running for the Dev Namespace.

**Comment by ayushjainid** [comment]
Validated same in the Sprint call.
