### ISSUE TITLE
Add and Implement an Action endpoint route for Addresses

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#74]
**As a** [role]
**I need** [function]  
**So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by Akshama** [comment]
We will implement action route for Customer.
