### ISSUE TITLE
Add and Implement an Action endpoint route for Customer - Notify a Customer

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#76]
**As a** Customer Service Manager/API User
**I need** the ability to notify a customer using his email
**So that** I can keep the customer updated of important activities
   
 ### Details and Assumptions
 * Database Model for Customers is as per #3
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is up and running
 When executing the action - notify a customer, PUT request on customers/{customer_id}/notify
 Then the customer with customer_id = {customer_id} will be notified through his/her email
```

**Comment by ayushjainid** [comment]
Duplicate of #57

**Comment by Akshama** [comment]
Not part of requirements for the project.
