### ISSUE TITLE
Add dev namespace to the Kubernetes cluster 

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#77]
**As a** API developer
**I need** add a dev namespace to the Kubernetes cluster 
**So that** I can deploy my services in a dev environment  
   
 ### Details and Assumptions
 * Cluster is up and running
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the cluster is up and running
 When I add a dev namespace to the Kubernetes cluster 
 Then I can deploy my services in a dev environment
```

**Comment by mwj10** [comment]
Dev namespace been created and ImagePullSecret been copied to the namespace

**Comment by Akshama** [comment]
![image.png](https://images.zenhubusercontent.com/63e52d33513305367f4b28bf/d98bb06b-e150-4da9-b6e6-4f1a02d296cb)
Able to see the namespace and the secrets in dev namespace
