### ISSUE TITLE
Need the ability to Create a Customer

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#9]
**As a** Customer Service Manager/API User
**I need** to be able to create a Customer Resource
**So that** I can add new Customer's Data.
   
 ### Details and Assumptions
The API should be able to accept all information based on the schema discussed in [issue #3](https://github.com/CSCI-GA-2820-SP23-003/customers/issues/3)

 ### Acceptance Criteria  
   
 ```gherkin
 Given all valid fields
 When calling a POST request on /customers
 Then HTTP.201 code and an url to the newly created Customer ( /customers/{id} ) should be returned.

 Given any invalid field(s) or duplicate values for unique field(s)
 When calling a POST request on /customers
 Then if its a duplicate value for a unique field return HTTP.409 (Conflict) else return HTTP.400.
```

**Comment by sreevishnu211** [comment]
**As an** API User
**I need** to be able to create a Customer Resource
**So that** I can add new Customer's Data.
   
 ### Details and Assumptions
The API should be able to accept:
- First Name
- Last Name
- Mobile Number
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a First Name and a Last Name with a unique Mobile Number
 When calling a POST request on /customers
 Then HTTP.200 code and an url to the newly created Customer ( /customers/<id> ) should be returned.

 Given either an invalid First or Last Name or a duplicate Mobile Number
 When calling a POST request on /customers
 Then HTTP.409 code should be returned.
```

**Comment by Akshama** [comment]
We might need to add username and password as fields here, and could store them in encrypted format for security.

**Comment by mwj10** [comment]
User name and password are covered in #3 and #30.
